#!/usr/bin/env python3
"""
Draws the favicon (app/icon.svg) and the PWA icons (public/icon-192.svg, public/icon-512.svg): the W from
Source Serif 4 SemiBold, the masthead's face, on the ink square. Pulled from the font as an outline rather than
drawn by hand (a hand-drawn W once read as the Wario logo) or set as <text> (a favicon has no webfont).

    python3 scripts/og/build-favicon.py      # needs: pip3 install fonttools brotli

Check any change at 16 px, not just 512: a hairline disappears at tab size.
"""
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
FONT = HERE / 'source-serif-4-semibold.woff2'
INK, PAPER = '#14130f', '#f6f4ef'
WIDTH_SHARE = 0.66  # the W's width as a share of the square
ICONS = [(ROOT / 'app/icon.svg', 32, 6), (ROOT / 'public/icon-192.svg', 192, 36), (ROOT / 'public/icon-512.svg', 512, 96)]


def glyph():
    font = TTFont(FONT)
    glyphs = font.getGlyphSet()
    name = font.getBestCmap()[ord('W')]
    path, bounds = SVGPathPen(glyphs), BoundsPen(glyphs)
    glyphs[name].draw(path)
    glyphs[name].draw(bounds)
    return path.getCommands(), bounds.bounds


def icon(size, rx, d, bounds):
    x0, y0, x1, y1 = bounds
    s = size * WIDTH_SHARE / (x1 - x0)
    tx = size / 2 - (x0 + x1) / 2 * s  # centre the glyph's box in the square
    ty = size / 2 + (y0 + y1) / 2 * s  # font units point up; SVG points down
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}">
  <!--
    The W from Source Serif 4 SemiBold, the same face as "Wesley Bard" in the header, so the tab icon and the
    masthead are one letterform. An outline, not <text>: a favicon has no webfont to fall back on.
    Generated by scripts/og/build-favicon.py; regenerate all three together.
  -->
  <rect width="{size}" height="{size}" rx="{rx}" fill="{INK}"/>
  <g transform="translate({tx:.3f} {ty:.3f}) scale({s:.5f} {-s:.5f})"><path d="{d}" fill="{PAPER}"/></g>
</svg>
'''


if __name__ == '__main__':
    d, bounds = glyph()
    for out, size, rx in ICONS:
        out.write_text(icon(size, rx, d, bounds))
        print(f'wrote {out.relative_to(ROOT)}')
